### ISSUE TITLE
Boxes out of format on home view when reducing screen size

### ISSUE THREAD

**Issue by tralcanx** [pungtas/tyron-permaweb-dapp#1]
I noticed that some boxes get out of format on the home view when reducing the screen size (in the browser and tablet too).
![image](https://user-images.githubusercontent.com/45559650/115706120-ad444180-a343-11eb-857d-4c6420f90322.png)
I tried changing the 'style' prop to a different tag at https://github.com/pungtas/tyron-permaweb-dapp/blob/master/src/components/home.js - but when all boxes have the proper style then the About box gets too much to the left and disappears (not allowing to scroll to the left).

**Comment by Schoonmoeder** [comment]
This has to do with the display flex
check out this to decide what you want to do
https://webdesign.tutsplus.com/tutorials/a-comprehensive-guide-to-flexbox-ordering-reordering--cms-31564

**Comment by tralcanx** [comment]
thank u @Schoonmoeder! I think @dorian30 is on it as well

**Comment by Dorian30** [comment]
Yes, I already solved this. I'll open a PR today.

**Comment by tralcanx** [comment]
Solved with PR https://github.com/pungtas/tyron-permaweb-dapp/pull/3

Muchas gracias @Dorian30!
